GEt http://127.0.0.1:8000/api/ticket/tickets/
Content-Type: application/json

{}

###
POST http://127.0.0.1:8000/api/ticket/tickets/
Content-Type: application/json

{
    "nomClient": "nomClient",
    "prix": "prix",
    "codePayement": "codePayement",
    "salle": 1,
    "place": 1,
}

###
POST http://127.0.0.1:8000/api/ticket/tickets/1/
Content-Type: application/json

{ }
