GEt http://127.0.0.1:8000/api/ticket/tickets/
Content-Type: application/json

###

POST http://127.0.0.1:8000/api/ticket/tickets/
Content-Type: application/json

{
    "nomClient": 1,
    "prix": "prix",
    "salle": 1,
    "place": 1,
    "seance": 1,
}

###

GET http://127.0.0.1:8000/api/ticket/tickets/1/
Content-Type: application/json

###

PUT http://127.0.0.1:8000/api/ticket/tickets/1/
Content-Type: application/json

{
    "nomClient": "nomClient",
    "prix": "prix",
    "salle": 1,
    "place": 1,
    "seance": 1,
}

###

DELETE http://127.0.0.1:8000/api/ticket/tickets/1/
Content-Type: application/json
