# Generated by Django 5.0.7 on 2024-07-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=100)),
                ('prix', models.IntegerField(default=0)),
                ('codePayement', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.place')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.salle')),
            ],
        ),
    ]
