# Generated by Django 5.0.7 on 2024-08-13 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_cinema', '0001_initial'),
        ('Gestion_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.seance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='codePayement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.place'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='salle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.salle'),
        ),
    ]
