# Generated by Django 5.0.7 on 2024-08-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_cinema', '0007_alter_salle_places'),
        ('Gestion_ticket', '0004_alter_ticket_nomclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.seance'),
        ),
    ]
