# Generated by Django 5.0.7 on 2024-08-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_ticket', '0005_alter_ticket_seance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nomClient',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
