# Generated by Django 5.0.7 on 2024-07-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('nombreSalle', models.IntegerField(default=1)),
                ('longitude', models.FloatField()),
                ('latitute', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('prix', models.FloatField(default=0)),
                ('reservee', models.BooleanField(default=False)),
                ('libre', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=75)),
                ('duree', models.FloatField()),
                ('realisateur', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='films/')),
                ('dateSortie', models.DateField()),
                ('category', models.ManyToManyField(to='Gestion_cinema.categorie', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombrePlace', models.IntegerField(default=1)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.cinema', verbose_name='')),
                ('places', models.ManyToManyField(to='Gestion_cinema.place', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prix', models.FloatField(default=0)),
                ('heureDebut', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.film')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('longitude', models.FloatField()),
                ('latitute', models.FloatField()),
                ('altitude', models.FloatField()),
                ('cinema', models.ManyToManyField(to='Gestion_cinema.cinema', verbose_name='')),
            ],
        ),
    ]
