# Generated by Django 5.0.7 on 2024-08-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AlterField(
            model_name='salle',
            name='places',
            field=models.ManyToManyField(to='Gestion_cinema.place', verbose_name='places de la salle'),
        ),
    ]
