# Generated by Django 5.0.7 on 2024-08-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_cinema', '0003_film_category_alter_film_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='films/'),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.categorie'),
        ),
    ]
