# Generated by Django 5.0.7 on 2024-08-18 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_cinema', '0005_alter_cinema_id_alter_place_id_alter_salle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='cinema',
        ),
        migrations.AddField(
            model_name='cinema',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.ville'),
        ),
        migrations.RemoveField(
            model_name='salle',
            name='places',
        ),
        migrations.AddField(
            model_name='salle',
            name='places',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.place', verbose_name=''),
            preserve_default=False,
        ),
    ]
