# Generated by Django 5.0.7 on 2024-08-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_cinema', '0006_remove_ville_cinema_cinema_ville_remove_salle_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_cinema.place', verbose_name=''),
        ),
    ]
