# Generated by Django 5.0.7 on 2024-08-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_cinema', '0007_alter_salle_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.FileField(default='', null=True, upload_to='films/'),
        ),
    ]
