POST http://127.0.0.1:8000/accounts/api/login
Content-Type: application/json

{"username": "john_doe", "password": "john"}

###

POST http://127.0.0.1:8000/accounts/api/register/client
Content-Type: application/json

{"username": "john_doe", "password": "john", "email": "john@gmail.com", "first_name": "Doe", "last_name": "John"}

###

GET http://127.0.0.1:8000/accounts/api/test-token
Content-Type: application/json
Authorization: Token xxxxxxxxx

{}